"""add trigger for updateplayer score if reset all response

Revision ID: 2b281c3f428c
Revises: 0f43517b036e
Create Date: 2025-10-18 16:30:39.478640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b281c3f428c'
down_revision: Union[str, Sequence[str], None] = '0f43517b036e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
