"""updated response to store llm feed back and liked feedback from user

Revision ID: 9a499078b2fb
Revises: 01a99f929011
Create Date: 2025-10-08 17:30:28.974219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a499078b2fb'
down_revision: Union[str, Sequence[str], None] = '01a99f929011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('llm_feedback', sa.Text(), nullable=True))
    op.add_column('responses', sa.Column('liked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'liked')
    op.drop_column('responses', 'llm_feedback')
    # ### end Alembic commands ###
